### PR TITLE
default to using useUnifiedTopology option

### PR DESCRIPTION
**Pull request by bobmoff**
More info here: https://github.com/mongodb/node-mongodb-native/releases

### CODE REVIEW

**Comment by mpangrazzi** [comment]
can you add one or more tests as for `useNewUrlParser` option?

**Comment by bobmoff** [comment]
> can you add one or more tests as for `useNewUrlParser` option?

done!

**Comment by mathieudutour** [comment]
Hum that's a breaking change, isn't it? 
What's the reason to default to `true`?

**Comment by bobmoff** [comment]
DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to MongoClient.connect.

**Comment by mpangrazzi** [comment]
@mathieudutour IMHO it seems to be very similar to `useNewUrlParser` option. It's due to an internal change in `mongodb` module, and it's not listed as a breaking change in their docs.

**Pull request merged**
