### PR TITLE
MongoDB Insert deprecation (updated to insertOne/insertMany)

### PR DESCRIPTION
**Pull request by RobertoMachorro**
Added bindings and updated tests for insertOne/insertMany. Monk already supports bulkWrite.
This addresses issue #276 .

`
(node:30558) DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead.
`

### CODE REVIEW

**Comment by faradaytrs** [comment]
Could you please do the same for count()

**Comment by mathieudutour** [comment]
How about updating the `insert` method to either use `insertOne` or insertMany` depending on whether an array is passed instead of adding 2 new methods?

**Comment by RobertoMachorro** [comment]
> Could you please do the same for count()

@faradaytrs most probably will, also **group** is going to be deprecated in favor of aggregation, i saw some of the tests spitting that out

**Comment by RobertoMachorro** [comment]
> How about updating the `insert` method to either use `insertOne` or insertMany` depending on whether an array is passed instead of adding 2 new methods?

That's a great idea! Will do that for backwards compatibility, however, will still keep insertOne/Many because of upwards compatibility with MongoDB itself. The final say in all this - of course - is the Monk maintainers.

**Comment by osban** [comment]
@RobertoMachorro apparently the `fields` option is also deprecated, so if you could fix that too, that'd be great 🙂

**Comment by RobertoMachorro** [comment]
> @RobertoMachorro apparently the `fields` option is also deprecated, so if you could fix that too, that'd be great 🙂

@osban will do, but didn't see the warning? could you post more info about it?

**Comment by osban** [comment]
@RobertoMachorro here's the warning message: `(node:5151) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.`. It's when you only want the query to return certain fields. Do you need more info?

**Comment by RobertoMachorro** [comment]
> @RobertoMachorro here's the warning message: `(node:5151) DeprecationWarning: collection.find option [fields] is deprecated and will be removed in a later version.`. It's when you only want the query to return certain fields. Do you need more info?

That works, thanks - just needed some context.

**Comment by RobertoMachorro** [comment]
> let's even remove the other 2 methods, they are superfluous

@mathieudutour that makes sense, i'll remove the insertOne/inserMany calls. Some of the mongodb-cli intuitiveness will be out, though.

**Comment by mathieudutour** [comment]
I'd say a single `insert` is a more intuitive than 2 different calls? The API surface is smaller -> easier to remember

**Comment by RobertoMachorro** [comment]
@mathieudutour i'm making sure to match your code style, but I don't see a ternary operator anywhere on the source, do you prefer not to use them and go with regular if blocks?

**Comment by mathieudutour** [comment]
I do use ternaries, but maybe I’d write `const colcall = arrayInsert ? args.col.insertMany : args.col.insertOne` (eg. remove the unnecessary parentheses and add a space)

**Comment by RobertoMachorro** [comment]
> I do use ternaries, but maybe I’d write `const colcall = arrayInsert ? args.col.insertMany : args.col.insertOne` (eg. remove the unnecessary parentheses and add a space)

I had it like that originally, however, Node doesn't like that. I've seen that happen with functions that return a promise as opposed to a value:

```
stack: >
  Collection.insertMany
  (/Projects/monk/node_modules/mongodb/lib/collection.js:504:32)

  insert (/Projects/monk/lib/collection.js:322:12)

  /Projects/monk/node_modules/monk-middleware-wait-for-connection/index.js:8:16
at:
  line: 504
  column: 32
  file: /Projects/monk/node_modules/mongodb/lib/collection.js
  function: Collection.insertMany
type: TypeError
tapCaught: returnedPromiseRejection
test: collection find limit/skip data
source: |2

    return executeOperation(this.s.topology, insertManyOperation, callback);
  -------------------------------^
  };
...
```

**Comment by RobertoMachorro** [comment]
Thanks to all that can test, I'll start a count and find/fields update on a separate branch.

**Pull request merged**
