### PR TITLE
Replace expect.js with chai and test against newer versions of node

### PR DESCRIPTION
**Pull request by JaKXz**
@travisjeffery or @vkarpov15 could you review, if this project is still somewhat active? Looks like the TravisCI hooks need to be updated, but the tests passed for me running on node v5.10 :)

### CODE REVIEW

**Comment by vkarpov15** [comment]
Seems reasonable to me but I don't have push access to this repo :(

**Comment by travisjeffery** [comment]
LGTM, thanks!

**Comment by travisjeffery** [comment]
The tests pass for me running v5.9.1. When don't they pass for you?

**Comment by JaKXz** [comment]
screen shot 2016-04-11 at 1 56 54 pm

@travisjeffery 
```bash
$ node --version
v5.10.1
```

Also, chai's expect gives much nicer stack traces.

**Comment by JaKXz** [comment]
In any case, re-enabling the Travis hooks would be for the best.

**Comment by JaKXz** [comment]
Closing in favour of #132.

**Pull request closed without merging**
