### PR TITLE
feat(collection): uses countDocuments, added estimatedDocumentCount

### LINKED ISSUE #299: Update count to use countDocuments
The `collection.count()` method was marked as deprecated in version 3.1 of the [monogdb node driver](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#count) and two new methods were added, `collection.countDocuments()` and `collection.estimatedDocumentCount()`. From the documentation:

> To obtain an accurate count of documents in the collection, use `countDocuments`.
To obtain an estimated count of all documents in the collection, use `estimatedDocumentCount`.

It would be great if monk supported the new functions that were added.

### PR DESCRIPTION
**Pull request by bit-cmdr**
Updated `collection.count()` to point to `collection.countDocuments()` in the mongo driver. This was added in in version 3.1 and monk has a dependency of 3.2.3 or higher of the `mongodb` package, so there should be no concern about breaking changes. The `collection.count()` is deprecated in the `mongodb` package and suggests using `collection.countDocuments()` instead. Documentation was
updated to point to the `countDocuments` method on the MongoDB API reference. When the `countDocuments` method was added another method was added along with it, `estimatedDocumentCounts()`. This also adds that function to monk, the documentation was added for it and the typings file was updated to support it as well.

resolves #299

### CODE REVIEW

**Comment by SacDin** [comment]
when is this scheduled to be merged ?

**Comment by mpatino117** [comment]
When is this going to be merged ? Looks decent fix for deprecation warnings.

**Comment by w33ble** [comment]
Is this ever going to land? @mathieudutour offered a review of such a PR in [this comment](https://github.com/Automattic/monk/issues/297#issuecomment-593477731), but it doesn't look like that's happened. Anything any of us can do to help make this happen?

**Comment by mathieudutour** [comment]
Ah sorry, missed it.

I'd rather not expand the API surface, and use an option for `estimatedDocumentCounts` eg. `doc.count({estimate: true})`

**Comment by bit-cmdr** [comment]
I can make it an option and update the docs. Let me update the PR and we can discuss.

**Comment by bit-cmdr** [comment]
@mathieudutour I updated the `count` to use an `estimate` as suggested. I'm open to further changes if this isn't the right direction or just doing the count change for now and discussing estimated separately.

**Review by mathieudutour — APPROVED** [review]
Looks good to me 👍 
Thanks for the PR!

**Pull request merged**
