### PR TITLE
Use `setImmediate` on Node 0.10.x

### LINKED ISSUE #33: Recursive process.nextTick detected
Hey!

Since the last node version, I have this error : 
```
(node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.
```
for a simple : 
```
find({...}, { stream: true }).each(fn)
```
Any idea to fix that?

Thanks,
Philippe

### PR DESCRIPTION
**Pull request by nulltask**
resolves #33

### CODE REVIEW

**Comment by rauchg** [comment]
Please rebase. Great fix!

**Comment by nulltask** [comment]
merged!

**Comment by travisjeffery** [comment]
Thanks!

**Comment by nicholaswyoung** [comment]
Thanks @travisjeffery!

**Pull request merged**
