### PR TITLE
Update mongoskin to v2

### PR DESCRIPTION
**Pull request by ratson**
I have upgraded mongoskin to v2 and fixed the code to pass the tests.
This should fix  https://github.com/Automattic/monk/issues/93 and https://github.com/Automattic/monk/issues/111

For those who can't wait, feel free to try [my fork](https://www.npmjs.com/package/monkii) and [report issues](https://github.com/ratson/monkii/issues).

@travisjeffery Would you review the code and see if anything need to be improved?

### CODE REVIEW

**Comment by YasharF** [comment]
Any updates on merging this pull request?

**Comment by vnglst** [comment]
Any updates on merging this PR?

**Comment by LeNiglo** [comment]
Is there a way that this PR is merged ?
There is apparently no conflicts, so ... what's the matter ?

**Comment by ratson** [comment]
@LeNiglo Feel free to try out my fork, [monkii](https://github.com/ratson/monkii). I really don't see this will be merged soon as the author has not been replying any issues for quite a while.

**Comment by LeNiglo** [comment]
I'm already using it @ratson. But still ...

**Comment by YasharF** [comment]
I just emailed @travisjeffery to see if he can help out or if he can not, to find out who the right contact would be.

**Comment by YasharF** [comment]
By the way, the PR, is setting the dependencies to:

 "mongodb": "^2.1",
 "mongoskin": "~2.0.3",
 "mpromise": "0.5.1"	
 
However, I think there are newer versions for them at the moment.  Can you please update the versions?

mongoskin:  2.1.0 is the latest
mpromise: 0.5.5 is the latest

**Comment by ratson** [comment]
@YasharF I can not update this pull request as [monkii](https://github.com/ratson/monkii) is no longer a fork, here is [the updated pull request](https://github.com/Automattic/monk/pull/128).

**Comment by YasharF** [comment]
Is the intent of Monkii a replacement of Monk and calling Monk as an abandoned project?  If so, there are other pending pull requests and issues filed for Monk, are you planning to address them in Monkii?

**Comment by ratson** [comment]
I really wish there is [monk v2](https://github.com/Automattic/monk/issues/93#issuecomment-88261922), which will be a rewrite without `mongoskin`. Unfortunately, it is not happening.

`monkii` serve mainly for upgrading `mongoskin` and allow usage of the latest MongoDB driver. I am open to accept any bug fixes, or additional features that do not introduce breaking changes.

**Comment by YasharF** [comment]
I emailed Guillermo Rauch and also sent a message to Automattic Inc. to see if we can revive this package.  If not, we may just need to fork it, and blast the internet that monk is dead and our new replacement is ....  Please update your site, guide, etc and have them use our new package instead of Monk.

**Comment by rauchg** [comment]
Unfortunately I'm not with Automattic anymore @YasharF! I don't have push access to this :(

**Pull request closed without merging**
