### PR TITLE
Added map reduce

### PR DESCRIPTION
**Pull request by IanSchweer**
Added (basic) map reduce to monk. Tests still to come.

### CODE REVIEW

**Comment by mathieudutour** [comment]
Thanks for the PR!

What's the reasoning behind changing the API the function (`map, reduce, options` -> `col, map, reduce, finalize, args, remove, opts`)

**Comment by IanSchweer** [comment]
No good reason, but it felt a little nicer explicitly stating the output table and the finalize method. `remove` just adds the convince of removing the map reduce inputs. I am of course willing to re arrange the args / add more functionality.

**Comment by IanSchweer** [comment]
Hey @mathieudutour, sorry I got really busy with finals and haven't had a time to change the API to confirm with the mongo api. I will do that soon and ping you when it's done. Do you want me to keep this PR open while I do that, or close it and reopen later?

**Comment by mathieudutour** [comment]
I don't mind keeping it open. 
As a rule of thumb, there shouldn't be more than 2 arguments in an API call. Otherwise you need to remember the order of the arguments which is not nice. It's better to have an object so there is no order

**Pull request closed without merging**
